CREATE TABLE SAMPLE_USERS(
    USER_ID VARCHAR2(20) PRIMARY KEY,
    USER_NAME VARCHAR2(50) NOT NULL,
    USER_PASSWORD VARCHAR(20) NOT NULL,
    USER_EMAIL VARCHAR(100) UNIQUE,
    USER_PHONE VARCHAR(20), 
    USER_STATUS VARCHAR(20) DEFAULT 'ACTIVE',
    USER_CREATED_DATE DATE DEFAULT SYSDATE
);